services:
  tsys-vscode-server:
    image: gitpod/openvscode-server
    container_name: reachableceo-vscode-server
    restart: always
    ports:
      - 2006:3000
    volumes:
      - tsys-vscode-server:/home/workspace:cached

volumes:
  tsys-vscode-server: