services:
  web:
     build: .
     ports: 
      - 2007:2007
     depends_on: 
      - influxdbV1
     volumes:
       - .:/app
  influxdbV1:
    image: influxdb:1.8.4
    container_name: reachableceo-health-data
    ports:
      - "28086:8086"
    volumes:
      - reachableceo-health-data:/var/lib/influxdb
    restart: unless-stopped
volumes:
  reachableceo-health-data: