services:
  influxdbV1:
    image: influxdb:1.8.4
    container_name: reachableceo-health-data
    ports:
      - "8086:8086"
    volumes:
      - reachableceo-health-data:/var/lib/influxdb
    restart: unless-stopped
volumes:
  reachableceo-health-data: