version: '3'
services:
  fitly:
    image: ethanopp/fitly:latest
    container_name: fitly
    restart: always
    ports:
      - "3000:80"
    environment:
      - MODULE_NAME=src.fitly.app
      - VARIABLE_NAME=server
      - TZ=America/Chicago
      - TIMEOUT=1200
      - DASH_DEBUG=true
    volumes:
      - ./config:/app/config