version: "3"
services:

  client:
    build: .
    networks:
      - habitica
    environment:
      - BASE_URL=http://tsys1:2008
    ports:
        - "2008:8080"
    command: ["npm", "run", "client:dev"]
    depends_on:
      - server

  server:
    build: .
    ports:
      - "3008:3000"
    networks:
      - habitica
    environment:
      - NODE_DB_URI=mongodb://mongo/habitrpg
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6
    ports:
      - "27017:27017"
    networks:
      - habitica

networks:
  habitica:
    driver: bridge