services:
  wael:
    container_name: reachableceo-wael
    image: reachableceo-wael:latest # increment this number (or set the env value in your .env) to force portainer to rebuild the image https://github.com/portainer/portainer/issues/6288
    restart: always
    ports:
      - "2009:3009" # Must be supplied by shell or in .env file
    env_file:
      - ./wael.env
    volumes:
      - "${HOST_DATA_PATH:-/default/path}:/workspace/prisma/data" # Must be supplied by shell or in .env file
    user: node
